Pentatonictritones/dw 139/create end time for ibal
GetAlluo/liquidity-direction-protocol pull request #101
Opened 2022-09-08 10:42 UTC by pentatonictritones

1. Two superfluid resolvers for:
a. Liquidation protection
b. Allowing an endDate / duration to be put on streams

2. Deployment details and OZ scripts

3. Small cleanup

2022-09-27 22:52 UTC, 0xtuytuy commented
@pentatonictritones @zayk00v where are we here ?

2022-09-28 02:35 UTC, pentatonictritones commented
> @pentatonictritones @zayk00v where are we here ?

@zayk00v reviewed it and we deployed it together. It is on both mumbai and polygon.

Maybe @zayk00v wants to do some formatting / cleanup before this is merged with master?

2022-10-27 07:49 UTC, alexanderem49 approved these changes
LGTM

2022-10-27 07:53 UTC, 0xtuytuy requested changes
A few things to look at.

2022-10-27 07:53 UTC, 0xtuytuy commented on contracts/Farming/Polygon/IbAlluo.sol
> +    // function createFlow(address receiver, int96 flowRate, uint256 toWrap, bytes memory ctx, bytes memory userData, uint256 timestamp) external {
do we need to keep this as a huge comment?

2022-10-27 07:53 UTC, 0xtuytuy commented on hardhat.config.ts
> +<<<<<<< HEAD
looks like there are some merge headers left here

2022-10-27 07:53 UTC, 0xtuytuy commented on scripts/deploy/priceFeeds/deployFeedsPhase1.ts
> +        // {
do we need to keep this comment ?

2022-10-27 07:53 UTC, 0xtuytuy commented on test/farming/StIbAlluo.ts
> +            // https://dashboard.tenderly.co/pentatonictritones/project/simulator/fd708bad-b2d9-4e7b-8949-93a07834fdd7
Do we want to keep this again ?

2022-10-31 17:48 UTC, Jorge-Lopes commented on contracts/Farming/Polygon/IbAlluo.sol
> +    // function createFlow(address receiver, int96 flowRate, uint256 toWrap, bytes memory ctx, bytes memory userData, uint256 timestamp) external {
Comment deleted on commit [b44c08d](https://github.com/GetAlluo/liquidity-direction-protocol/commit/b44c08d8ce2487eb8aa39ee5efb029e97aaf03fe)

2022-10-31 17:49 UTC, Jorge-Lopes commented on hardhat.config.ts
> +<<<<<<< HEAD
Conflict resolved on commit [b44c08d](https://github.com/GetAlluo/liquidity-direction-protocol/commit/b44c08d8ce2487eb8aa39ee5efb029e97aaf03fe)

2022-10-31 17:49 UTC, Jorge-Lopes commented on scripts/deploy/priceFeeds/deployFeedsPhase1.ts
> +        // {
Comment deleted on commit [b44c08d](https://github.com/GetAlluo/liquidity-direction-protocol/commit/b44c08d8ce2487eb8aa39ee5efb029e97aaf03fe)

2022-11-01 00:27 UTC, 0xtuytuy approved these changes
lgtm

2022-11-01 00:27 UTC, merged