Flow changes
GetAlluo/liquidity-direction-protocol pull request #112
Opened 2022-11-16 09:35 UTC by pentatonictritones

1. Quality of life changes to for deposit to return number of iballuousd minted,  only wrap tokens when creating flow if towrap>0. 

2. Small cleanup by removing functions not needed and fix tests

3. Write frontend scripts to grab enddate through events

2022-11-16 09:37 UTC, pentatonictritones commented
@zayk00v can you pls double check that the upgrade is safe by inspecting storage? I have checked once but want to double confirm. I will upgrade our staging environment first

2022-11-29 13:47 UTC, alexanderem49 approved these changes

2022-11-30 10:32 UTC, 0xtuytuy requested changes
Just 2 small comments regarding keeping comments.

2022-11-30 10:32 UTC, 0xtuytuy commented on contracts/Farming/Polygon/IbAlluo.sol
> +//    function setUpdateTimeLimit(uint256 _newLimit)
Do we need to keep this here?

2022-11-30 10:32 UTC, 0xtuytuy commented on contracts/Farming/Polygon/IbAlluoOld.sol
> +    // /// @notice Wraps and creates flow with context
same here, do we need to keep this massive comment here ?

2022-11-30 10:38 UTC, pentatonictritones commented on contracts/Farming/Polygon/IbAlluo.sol
> +//    function setUpdateTimeLimit(uint256 _newLimit)
Yes, this was commented out for release because of storage constraints. We need to reintroduce this for the next release so I am leaving it there.

2022-11-30 11:13 UTC, pentatonictritones commented on contracts/Farming/Polygon/IbAlluoOld.sol
> +    // /// @notice Wraps and creates flow with context
This is IbAlluoOld.sol which is used to check upgrade safety. IbAlluo.sol is the one deployed.

In that version, this is removed. Of course adding/removing this won't affect storage layout but in the spirit of keeping everything exactly it was / is deployed in prod, I think it is fine.

2022-11-30 13:48 UTC, 0xtuytuy approved these changes
LGTM

2022-11-30 13:48 UTC, merged