Big Cleaning
GetAlluo/liquidity-direction-protocol pull request #96
Opened 2022-08-17 16:25 UTC by zayk00v

2022-08-25 09:45 UTC, pentatonictritones requested changes
Just these two small things. The rest looks good because it is mostly shuffling around files for cleaning that we have previously reviewed.

2022-08-25 09:45 UTC, pentatonictritones commented on contracts/Farming/LiquidityHandler.sol
> +        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
This was added for tests only so can we remove this

2022-08-25 09:45 UTC, pentatonictritones commented on hardhat.config.ts
>          enabled: true,
Let's clean this up a little bit.

I think : 

1. Add all the networks we are using 
2. Add the updated env.example to the PR

2022-08-26 06:58 UTC, pentatonictritones approved these changes

2022-08-26 10:57 UTC, 0xtuytuy approved these changes
LGTM

2022-08-26 10:58 UTC, merged